### ISSUE TITLE
Set up the new deals page

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#85] opened 2019-02-18 17:33 UTC
Please let me know when:
1. The new deals information page
2. The new deals terms of service page
are set up, so I can start populating them.

The pages will contain a banner, side menu and a main section, as shown in this example:
[https://drive.google.com/open?id=1zSL3uz-8Rl5xFMo4QFkirmByHl20JQJB](url)

The side menu will be based on the respective Trello cards:
- Create a Deals page for users
- Create a Terms page for the user's deals

Populating the pages with information and pictures will be dealth with in another issue.

**Comment by buckwierd** [comment] 2019-02-18 17:33
![](https://github.trello.services/images/mini-trello-icon.png) [Create a Deals page for users](https://trello.com/c/hE4eX69R/42-create-a-deals-page-for-users)

**Comment by buckwierd** [comment] 2019-02-18 17:34
![](https://github.trello.services/images/mini-trello-icon.png) [Create a Terms page for the user's deals](https://trello.com/c/OGh3TNHp/45-create-a-terms-page-for-the-users-deals)

**Comment by lcoenen** [comment] 2019-02-22 07:50
Just so we're clear, I am 
1. creating two new pages on the model of https://www.whichost.com/terms-of-service
2. removing the deal page from there
3. In the new page, adding two section "deals" and "terms of service".

Is it correct? To be quite honest I am not visualising how this is supposed to be architectured. Maybe I can quickly draw it this evening so we're clear about that? I don't want to create everything and then realize this is not what you wanted.

**Comment by buckwierd** [comment] 2019-02-22 08:28
No. Not correct. Wait with this. We still didn’t defined the side menu content yet. This is something that Carlos and me will define either today or tomorrow, so you can start work.

**Comment by buckwierd** [comment] 2019-02-23 13:31
@lcoenen please set up the new deals page where we will present the deals for the customers (users/guests) as follows:

1. Area for banner. Include here h1 and h2 elements (like on our home page "Celebrate Anywhere" and "The largest online community to book parties and celebrations");

2. First side menu item called "What is this?"
Here we explain shortly what the deals page is about.
This page will only contain text.

3. Second side menu item called "Birthday Deal"
Here we'll give the details of the deal in form of pictures and text.
We will also provide the option of contacting us over two buttons "Email" and "Book a call".
Please include at the end of the page an accordion with two sections. One will be called "Terms" and the other one will be called "Examples". The CSS will be dealt with after setting everything up.

4. Third side menu item called "Hen & Stag Deal"
Hide for the time being from the side menu. Although this item will be hidden for the moment, we need the page so we can continue working on it asap.
This page will be build up in the same way like the "Birthday Deal" page.

5. Forth side menu item called "Corporate Deal"
Will be build like the "Birthday Deal" page.

Here's an example based on the "Birthday Deal" page:
![deal_layout_v01](https://user-images.githubusercontent.com/45966402/53286952-5ba4ca00-376d-11e9-9d94-6e48528507c5.png)

**Comment by lcoenen** [comment] 2019-02-25 20:21
All right, so the issue here is that the system right now is simply using a `StaticPages`  containers that hold every pages. Stay tuned.

**Comment by lcoenen** [comment] 2019-02-25 20:23
The branch `set-up-deal-pages` have been opened for this issue.

**Comment by lcoenen** [comment] 2019-02-25 21:40
I started working on that and created a page, but there's a lot of boilerplate involved. The skeleton should be done by wednesday.

**Comment by lcoenen** [comment] 2019-02-26 18:04
@buckwierd could you pull `set-up-deal-pages` and start populating it? I created the birthday deal page :) It's in `src/containers/birthdayDealPage/birthdayDealPage.js`, and the content is in `src/components/birthdayDeal/birthdayDeal.js`. 

I cannot add the banner, could you do it on one page? I'll add it in a separate component so I can add it later on on other pages.

**Comment by lcoenen** [comment] 2019-02-27 13:44
Guys I have an issue with the layout. In the current code, it is not possible to add a Hero like on the landing page. I am looking for a possibility to add it... but it's not trivial.

**Comment by buckwierd** [comment] 2019-02-27 16:28
What’s a Hero?

**Comment by buckwierd** [comment] 2019-02-27 17:08
I'm on the birthday deal now ;)

**Comment by buckwierd** [comment] 2019-02-27 17:12
@lcoenen I'm on the branch "set-up-deal-pages" and I'm getting this error on localhost after I enter "yarn dev" in the terminal console:
![screenshot 2019-02-27 at 17 10 42](https://user-images.githubusercontent.com/45966402/53508980-c5490f00-3ab2-11e9-99c6-67fdb30a2a89.png)

I didn't created a new issue in my local GitHub software. I fetched the prigin and selected the new issue "origin/set-up-deal-pages". Can you help?

**Comment by lcoenen** [comment] 2019-02-27 17:15
Yes. Just create a `.env` file with the following content:

```
    
# Mandatory configuration

REACT_APP_SHARETRIBE_SDK_CLIENT_ID=2e29c0e6-72e8-4ee6-a59d-4984b7e8d6e1
REACT_APP_STRIPE_PUBLISHABLE_KEY=
REACT_APP_MAPBOX_ACCESS_TOKEN=

# Or set up an alternative map provider (Google Maps). Check documentation.
# REACT_APP_GOOGLE_MAPS_API_KEY=

# Defaults
#

REACT_APP_SHARETRIBE_MARKETPLACE_CURRENCY=EUR
REACT_APP_CANONICAL_ROOT_URL=http://localhost:3000

# This is overwritten by configuration in .env.development and
# .env.test. In production deployments use env variable and set it to
# 'production'
REACT_APP_ENV=production


# Options. Uncomment and set to test.
#

# REACT_APP_SHARETRIBE_USING_SSL=true
# SERVER_SHARETRIBE_TRUST_PROXY=true
# REACT_APP_PUBLIC_SENTRY_DSN=change-me
# SERVER_SENTRY_DSN=change-me
# REACT_APP_CSP=report
# BASIC_AUTH_USERNAME=sharetribe
# BASIC_AUTH_PASSWORD=secret
# REACT_APP_GOOGLE_ANALYTICS_ID=change-me
REACT_APP_SHARETRIBE_SDK_BASE_URL=https://flex-api.sharetribe.com/.


# Features
#

REACT_APP_AVAILABILITY_ENABLED=true
REACT_APP_DEFAULT_SEARCHES_ENABLED=true
```

**Comment by buckwierd** [comment] 2019-02-27 17:48
Thanks but I need more details. Where do I put the file? Does it have to have a name like "abc.env" ?

**Comment by buckwierd** [comment] 2019-02-27 18:30
The basic coding is done and can be viewed here
https://jsfiddle.net/RaduSighencea/6fzy97hx/

Waiting for Loic to help fix the localhost issue with the "yarn dev" error.

**Comment by lcoenen** [comment] 2019-02-27 18:46
@buckwierd on the root of the project, and no, just call it `.env` :) This is because I removed the API keys from the project since it should be private. The one we use are test ones, but still, they should be kept private.

**Comment by buckwierd** [comment] 2019-02-27 18:53
@lcoenen thanks! Works fine ;) I'm working on the deal now. I'll try to add the banner first. Can you take a look at the black line in the side menu (the one symbolising which menu item is active)? It doesn't matter which item is active, it stays with "How it works".

**Comment by buckwierd** [comment] 2019-02-27 19:10
@lcoenen Issue with the side menu: Both "Birthday deal" and "Corporate deal" are showing the same page. It looks the page "Birthday deal" is linked to both. FYI ;)

**Comment by lcoenen** [comment] 2019-02-27 19:12
@buckwierd The first issue will be fixed, but for the second one, are you sure? I copied the page from DealsPage, so it's normal they both have the same content at first.

**Comment by lcoenen** [comment] 2019-02-27 19:13
@buckwierd I'm currently working on the banner, I may have something to ask you soon, stay tuned.

**Comment by buckwierd** [comment] 2019-02-27 19:15
@lcoenen was thinking about that but I removed the buttons from the birthday deal page and they disappeared from the corporate page too. Maybe you mean the "How it works" page, because there nothing changed after I changed the birthday deal page.

**Comment by lcoenen** [comment] 2019-02-27 19:15
Let me check.

**Comment by buckwierd** [comment] 2019-02-27 19:35
Note to myself:
Having issues with the html and css. Both are not being recognized. Will have to transform the fiddle css to the flex type of css.

**Comment by lcoenen** [comment] 2019-02-27 20:26
@buckwierd The issue should have been fixed. Please re-pull my change.

In `DealsPage.js`, you will find this code:

`				<LayoutWrapperHero>
					<div className={css.heroContent}>
						<h1 className={css.heroMainTitle}>
							<FormattedMessage id="DealsPage.title" />
						</h1>
						<h2 className={css.heroSubTitle}>
							<FormattedMessage id="DealsPage.subTitle" />
						</h2>
					</div>
				</LayoutWrapperHero>
`

The goal is to style this as in `LandingPage`, could you have a look at that? I tried, but no chance.

**Comment by lcoenen** [comment] 2019-02-28 15:56
I added the banner and the content, there's still styling issue and we have to add the actual content.

**Comment by buckwierd** [comment] 2019-02-28 19:05
Thanks @lcoenen . I had to commit my changes before pulling your updates. I hope this is fine :)

**Comment by buckwierd** [comment] 2019-02-28 19:26
@lcoenen I'm having an issue. When I save a small change on the BirthdayDeal, I'm getting a blank page. I've committed again just now, maybe you can see something that I can't see.

This is the code that I'm adding:
<div className={css.post_container}>
	  	<div className={css.image}
        style="background-image:url('https://ae01.alicdn.com/kf/HTB13zAXIFXXXXbxXFXXq6xXFXXX7/New-Arrival-2014-Mens-Flared-Jeans-Men-s-Bell-Bottom-Denim-Male-Big-Horn-Jean-Flare.jpg');">
		</div>
		<div className={css.desc}>
  <h3 className={css.postTitle}>Post title</h3>
   <p>Description here asjhd skdhf kasdhf askdfh ;alskdf lasdfj askdjfh kasdhf kasjd hf ere asjhd skdhf kasdhf askdfh ;alskdf lasdfj askdjfh kasdhf kasjd hf ere asjhd skdhf kasdhf askdfh ;alskdf lasdfj askdjfh kasdhf kasjd hfere asjhd skdhf kasdhf askdfh ;alskdf lasdfj askdjfh kasdhf kasjd hf
   </p>
   		</div>
   		<div className={css.readMore}>
  <a href="#" target="_blank">Read more about the terms &nbsp;<i style="font-size:18px" className={css.fa}>&#xf101;</i></a>
  		</div>
  	</div>

Cheers.

**Comment by buckwierd** [comment] 2019-02-28 19:27
Is it maybe because I'm trying to use an icon from FontAwesome and it's not connected to our platform?

**Comment by buckwierd** [comment] 2019-03-02 09:50
@lcoenen can you please take a look at this error? I'm one step forward and the page is at least trying to load. If you can fix the inline styling code, I might be able to finish the deals page this weekend :) I used the format from your CSS.md file.

ERROR:
./src/components/BirthdayDeal/BirthdayDeal.js
Syntax error: Unexpected token, expected } (21:27)

  19 | 	  <div className={css.postContainer}>
  20 |   <div className={[css.image, css.imageLeft]}
> 21 |   		style={background-image: "url('https://ae01.alicdn.com/kf/HTB13zAXIFXXXXbxXFXXq6xXFXXX7/New-Arrival-2014-Mens-Flared-Jeans-Men-s-Bell-Bottom-Denim-Male-Big-Horn-Jean-Flare.jpg')"}>
     |   		                       ^
  22 |   </div>
  23 |   <div className={css.desc}>
  24 |   <h3 className={css.postTitle}>Post title</h3>

**Comment by buckwierd** [comment] 2019-03-02 09:51
<img width="1002" alt="screenshot 2019-03-02 at 09 51 36" src="https://user-images.githubusercontent.com/45966402/53680262-ceafc280-3cd0-11e9-8bba-05d465557e15.png">

**Comment by buckwierd** [comment] 2019-03-02 10:56
Sent an email to Sharetribe's support team.

**Comment by buckwierd** [comment] 2019-03-03 10:54
Sharetribe replied that an expert will get back to me on Monday.

**Comment by buckwierd** [comment] 2019-03-04 14:32
Sharetribe provided this link as a reference to React and CSS:
https://reactjs.org/docs/dom-elements.html#style

Will check it out later.

**Comment by buckwierd** [comment] 2019-03-04 21:03
The Birthday Deal page is being build. Here's an interim result. Sharetribe was not useful in their support reply so I took a look at HTML5 semantic and could find a good solution. I had to get rid of the border and I've added a underline for the text to indicated that the text is linked to the image. Coding will be continued in the next days.
![screenshot 2019-03-04 at 20 59 13](https://user-images.githubusercontent.com/45966402/53762716-b900ef80-3ec0-11e9-94fd-370375cc5fb7.png)
 
Next challenge:
Float the items correctly for mobile devices viewports.

**Comment by buckwierd** [comment] 2019-03-04 21:04
The coding is still locally on my mac. Nothing was pushed nor committed.

**Comment by buckwierd** [comment] 2019-03-05 18:42
@lcoenen and @RohrerHope pushed the basic design of the Birthday Deal over the branch set-up-deal-pages. Please push to staging so that you guys can take a look at it and get back to me in case something is not behaving correct. 

I'll continue working on it in the next days.

**Comment by lcoenen** [comment] 2019-03-06 13:21
This have been pushed to `staging`.

**Comment by RohrerHope** [comment] 2019-03-06 15:22
Great work on the Birthday deal page. I'll share some thoughts later today. I've also taken a screenshot and shared it with Treasa for her feedback as a user.

For the Corporate Deal page, I shared some days ago a Google Doc with the text message for that section. This is the Google Doc: https://docs.google.com/document/d/1W7sWQVRw-Y1V95gNdveOMBiLNrL0f2Iv__C3uzVVwZ4/edit# 

👍 Thanks

**Comment by RohrerHope** [comment] 2019-03-06 15:24
BTW, as per the Birthday Deal doc, we can give up to €230.00 and not €200.00. 👍 

https://docs.google.com/document/d/13mH-1249yVJTy3R1mcSPD6cpCYqN8TquhAJd2RCXVt8/edit

**Comment by RohrerHope** [comment] 2019-03-06 18:36
**Feedback/Improvement points from me and Treasa**

1. We are mentioning three steps, so we should say which is step 1, 2 and 3. It looks strange when you read "follow these steps" and then there's no reference to them.
1. Some of the English sounds weird, so we just made it sound more normal.
1. Some changes in sentences to sell the message better.

**Improvements for the texts**

Birthday Deal!
Book your birthday party through Whichost and treat yourself!
Follow these three simple steps to receive up to €230 as a birthday gift from us.
 
Happy Birthday!
At Whichost we are all about giving back! That’s why we reward you for celebrating with us.
Search for a pub, select “Birthday party” under occasion type and book it (step 1).

Have a great time!
Take your friends out and show them how to party without leaving a mess. It’s all about leaving the place as you would like to find it (step 2).

Let us know how it was!
Show us how you party. Gather your party group together, take a picture, post it on social media and let us know how your party was by tagging Whichost (step 3).

 👍🏼

**Comment by buckwierd** [comment] 2019-03-07 08:24
Thanks. I’ll work on it ASAP. I will also add the contact buttons below the steps and the terms in an accordion below the contact buttons.

**Comment by buckwierd** [comment] 2019-03-08 21:54
@lcoenen @RohrerHope the Birthday Deal Page is done.

This is what's missing:
- The hyperlinks
- The accordion.This needs to be implemented by Loic. One accordion tab for the Terms and Conditions and another one for the examples. I've added the sections with classes **.termsAndConditionsAcordion** and **.examplesAcordion** (I hope this helps you Loic)
- The updated text
- The mobile devices viewport

Will be dealing with them this weekend.

Was pushed over set-up-deal-pages

**Comment by lcoenen** [comment] 2019-03-11 20:56
@buckwierd The accordion have been created as a components. It have been pushed to you. It just need styling (I created a very ugly styling).

I was expecting a static *styled* version of the page. Sorry for the misunderstanding.

**Comment by buckwierd** [comment] 2019-03-12 18:59
The accordion was styled without using "src/components/Accordion/Accordion.css" because I didn't knew how to trigger the open and close statuses of it. The changes have been pushed. Will continue working on the page. At the moment I have an issue with linking links to the buttons over the <button> tag.

**Comment by lcoenen** [comment] 2019-03-12 19:09
What's the issue? Explain :) I can have a look

**Comment by buckwierd** [comment] 2019-03-12 19:24
Issues solved. Pushed the new changes again. @RohrerHope your text was added (altered). The links for the steps were added. The buttons links were added over:

<form action="https://www.w3docs.com/" method="get" target="_blank">
         <button type="submit">Click me</button>
</form>

**As there is actually no form and no data is submitted, this may be semantically incorrect. However, this markup is valid.**

That's it for now. I'll continue working on the "What is this?" and Corporate Deal page.

@RohrerHope the table with the vouchers will probably be placed between the 3rd picture and the get in touch area, right?

**Comment by buckwierd** [comment] 2019-03-12 19:29
@lcoenen please push it to staging so @RohrerHope can take a look at it too :)

**Comment by RohrerHope** [comment] 2019-03-12 19:34
@buckwierd 

Regarding the location of the table, if I remember the design correctly then yes, the table with the clarification of the gift card values per size party and day would come right after the third image.

Let's make sure that before we show the table we provide some context on what it is, maybe a sub-title in that area with a quick description or introduction to the table. That's an idea.

**Comment by RohrerHope** [comment] 2019-03-12 20:44
**First observations:**

Good job on this. It's coming along 😃 

1- The T&Cs and the examples texts are based on an old version of the Birthday deal.

@buckwierd I don't know where you are getting the text from, but this is the document: https://docs.google.com/document/d/13mH-1249yVJTy3R1mcSPD6cpCYqN8TquhAJd2RCXVt8/edit#

You will see the differences, very clearly. Not only in the T&Cs, but also in the examples.

2- In this sentence "Don´t hesitate to contact us via the highlited options below. As we don´t sleep at all, we´ll get back to you very soon." 

The apostrophe symbol you are using isn't the correct one. See the difference "Don't" and the one you have there "Don´t".

The word "highlited" is spelt "highlighted".

3- In the T&Cs and Examples, there are no lines of space in between any of the bullet points. That makes it very hard to read. In our internal template doc for Google Docs, we have a rule for this. Let's apply that same rule here to make it easier to read. We need white lines of separation.

4- In the mobile version, the buttons are one next to the other, glued. There's no separation between them.

Keep it up 👍 Thanks.

**Comment by buckwierd** [comment] 2019-03-13 19:16
@RohrerHope @lcoenen 

1. Fixed.

2. Fixed.
The wrong apostrophe is a coding thing as ' is reserved for JaveScript. I've replaced everyhting with ' in the hope that the code won't break. At the moment everything works fine on my end.

3. Fixed.

4. Fixed.

The only think that I'm working now on is the section with the table. I need to find a way to put in there nicely. I'll keep you up to date.

Nothing was pushed yet. I'll try to work on as much as possible before I push the changes.

**Comment by buckwierd** [comment] 2019-03-13 19:31
The tables of the Birthday Deal will be combined in one table, to keep it simple. Here's an example of how the table will look like. Pay attention to the nicely solved responsiveness, where every single line gets its own headings on mobile devices:
https://colorlib.com/etc/tb/Table_Responsive_v2/index.html

**Comment by buckwierd** [comment] 2019-03-13 19:41
Here’s a sketch of how the table will look like. Hope it’s readable:

Desktop view with headlines and rows:
![Image](https://i.imgur.com/RRLDdLP.jpg)

Mobile view with separated boxes containing each headline and the related rows:
![Image](https://i.imgur.com/TIX9ckv.jpg)

Will be working on it tomorrow.

**Comment by buckwierd** [comment] 2019-03-14 20:27
The discussed table can't be implemented since it's written in a language that is not compatoble with our react. The changes from yesterday were pushed to Loic so he can implement this simple table which is 100% compatible with our react:
https://codesandbox.io/s/43ml13vq19

Waiting for Loic to give his go so I can populate the new table.

**Comment by buckwierd** [comment] 2019-03-14 22:11
Commited the newest changes. One conflict occurred, which I don't know what it is. @lcoenen 
Line 93 in the BirthdayDeal.js showed this:
`>>>>>>> 250630d5a7823532b3ff2b225c9b1a8d1c110bf9`

Now it's failing to compile on my local host. Here's the error:
`Failed to compile
./src/components/BirthdayDeal/BirthdayDeal.js
Syntax error: Unexpected token (46:1)

  44 | 			</section>
  45 | 
> 46 | <<<<<<< HEAD
     |  ^
  47 | 			<section className={css.boxes}>
  48 | 				<div className={css.container}>
  49 | 					<div className={css.boxRight}>`

The new pricing table is also at a wrong position. Please tale a look at it Loic.

@RohrerHope 
This is what was updated:
- What's this? page
- Birthday deal page
- Employee benefit page
- Side menu titles

This is what's missing:
T&C on the Employee benefit page

**Comment by lcoenen** [comment] 2019-03-14 22:19
@buckwierd I told you, this can happens. What you see are git markers of the two version. You have to delete the line with `>>>>>>>>>` and simply integrate the change.

Please read https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging. 

For the position of the table, you just have to mode the `<PricingTable />` tag in `src/components/BirthdayDeal/BirthdayDeal.js`

**Comment by buckwierd** [comment] 2019-03-15 17:24
Full deals page coded. 
@lcoenen was committed and pushed. Please push to staging, so we can discuss it today. Please also inform Carlos when it's pushed.

@RohrerHope please take a look at it as soon as Loic pushed it to staging.

Let's discuss what the next steps are.

**Comment by RohrerHope** [comment] 2019-03-15 20:50
@buckwierd 

Great job on the deals page and the employees benefit one. 👏 

**As we talked today, here are the comments for the Birthday deal page:**

1. The T&Cs are still in the old version, same as the Examples. This is the current versions for both: https://docs.google.com/document/d/13mH-1249yVJTy3R1mcSPD6cpCYqN8TquhAJd2RCXVt8/edit#. We can't launch with the old versions. Please have a review of all of it so that they match the new versions, both T&Cs and Examples. Thanks.

1. We can simplify the table, as we talked. Here is an example of we talked:

![Screen Shot 2019-03-15 at 20 34 19](https://user-images.githubusercontent.com/39112974/54460558-cb511800-4761-11e9-99ce-e1fa7c8febaa.jpg)

**As we talked today, here are the comments for the Employees Benefit page:**

1. I just realised this. Let's please change everywhere where it says "Employee Benefit" to "Employees Benefit", employee must be plural.

1. The text that wraps around the image looks off, especially because of that last line that falls under the image. An idea is that from the line "How many of your employees would be..." (that is next to the image), you put that under the image. So the only text next to the image is "Give your employees the benefit of..." that entire line.

1. The same idea for the table, except in this case with the Employees Benefit values.

1. The text that is right above the buttons, let's use the one below:

"If providing employees with great benefits is very important for your organisation, contact us and we will be more than happy to have a chat and provide you with detailed information about our Whichost Employees Benefit and how to implement it." 

Thanks 👍

**Comment by RohrerHope** [comment] 2019-03-16 11:08
@buckwierd 

**The recommend a pub form is the wrong one**

The link you have in the T&Cs for recommending a pub is the incorrect one. Please review this in both the Birthday Deal and the Employees Benefit.

This is the correct one: https://docs.google.com/forms/d/e/1FAIpQLSfr2dEghUT1VF1i9BWPsvZIJpnHe2FPVmCuoHJaAR3AXDe_GA/viewform

You will also find this link in the T&Cs of the Birthday Deal doc I shared in the comment above.

**Comment by buckwierd** [comment] 2019-03-17 11:44
@RohrerHope will do the link too.
You please make a habit to delete superseded forms, to avoid situations like this in the future.

**Comment by buckwierd** [comment] 2019-03-17 12:06
Tables altered.
Recommend a pub links fixed.
"EmployeeS" altered.
No. 2 "wrapped text" depends on the device resolution. No fix for mow.

The only thing that's missing now are the T&C of the Birthday Deal. I'll try to finish them today. Then we have everything done and ready to post the 3rd phase, about the Birthday Deal and Carlos can send out the sales emails.

@lcoenen This means you'll have to most probably push to staging and then master tomorrow no later than 4 pm, so I can post the social media articles at 8 pm.

@RohrerHope any other minor cosmetics will be fixed afterwards. We can't stretch the launch further, otherwise we won't ever launch it. 

I'll get back to you when I have the T&C of the Birthday Deal done, committed and pushed.

**Comment by buckwierd** [comment] 2019-03-17 12:32
Above mentioned alteration committed and pushed.

**Comment by RohrerHope** [comment] 2019-03-17 14:36
@lcoenen 

Let's please push to staging with time so we can all have a look at it.

Thanks 🤙🏼

**Comment by buckwierd** [comment] 2019-03-17 18:16
T&C fort he Birthday Deal updated. 
@lcoenen was pushed to you. Please push to staging/master.
@RohrerHope for future text alterations please use the "Suggesting" tool in Google Docs, so I can update the code more easily.

**Comment by RohrerHope** [comment] 2019-03-17 19:17
Good work on the deals page. 👍🏼

**Observations:**

1. In the "What's this" page, we are saying "Take a look at the menu on the left side and you'll see...". However, since most people will see this page from their mobiles, on mobile the menu is on the top.

![Screen Shot 2019-03-17 at 18 40 33](https://user-images.githubusercontent.com/39112974/54496210-81446f80-48e4-11e9-8391-73c742037804.jpg)

That's not good UX. The simplest solution for this is to change the text so it says: "Take a look at the menu and you'll see..." (basically we remove "on the left side" from the sentence).

This is easy to fix.

1. The mobile version has a lateral scroll. 

This is looking directly at the table:

![Screen Shot 2019-03-17 at 18 51 05](https://user-images.githubusercontent.com/39112974/54496371-6d017200-48e6-11e9-88d8-f1656390156d.jpg)

And this is the lateral scroll. Notice the menu at the top how it is to the left, which means we have a small lateral scroll to the right, most probably caused by the table I believe, because that scroll is not in the "What's this" page.

![Screen Shot 2019-03-17 at 18 51 13](https://user-images.githubusercontent.com/39112974/54496374-7d195180-48e6-11e9-8439-d050046b963a.jpg)

1. The elements in the image should be bullet points and not simple paragraphs. As they are designed like this in the Google Doc. This observation applies for both the Birthday deal page and the employees benefit page.

![Screen Shot 2019-03-17 at 18 58 08](https://user-images.githubusercontent.com/39112974/54496396-bf429300-48e6-11e9-9433-37900d964e8f.jpg)

1. We need to do something about how the tables look like on mobile. It's not clean. You can clearly see that there's enough space between the columns for more proper distribution of the text. Especially the column in the middle, which looks like it's shrunk by the other two.

![Screen Shot 2019-03-17 at 18 51 05](https://user-images.githubusercontent.com/39112974/54496436-2f511900-48e7-11e9-991a-e221d4244f82.jpg)

1. On Friday we talked about the text formatting and how we will use the capital letters. Example, "What's this" would be 'What's This". "Birthday deal" would be "Birthday Deal'. "Employees benefit" would be "Employees Benefit".

1. In the Employees Benefit page, the email corporate@whichost.com is not hyperlinked. It's plain text. This is the sentence that you will find it "If providing employees with great benefits is very important for your organisation, contact us at corporate@whichost.com and we will be more than happy to have a chat and provide you with detailed information about our Whichost Employee Benefit." This is also easy to fix.

This is what I have for now.

Thanks for the work on this page 👏

**Comment by lcoenen** [comment] 2019-03-17 19:30
I fixed the first text issue.

**Closed** 2019-03-22 19:11 UTC
Labels: urgent
