### ISSUE TITLE
Create a contact us form

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#74] opened 2019-02-14 13:15 UTC
While Aoife and my sister were asked to contact us, the question came up what if the user doesn't have a email software installed on his device? At the moment the standard software opens a new email and the user can write us a email.

As a solution we might take in consideration creating a simple contact us page with a simple email contact form, like the book a call form.

High end solution:
When the user goes on the new contact us page, he will see two options "Write us a email" and "Book a call". After choosing one of the options, the respective form shows up (collapses like an accordion for ex.)

**Comment by lcoenen** [comment] 2019-03-15 13:14
Duplicate of #72

**Comment by buckwierd** [comment] 2019-03-27 18:27
Reopening as this is not a duplicate of #72

**Comment by lcoenen** [comment] 2019-03-27 18:30
The page have been created. We just need to populate them. Tell me how is this different from #72?

**Comment by lcoenen** [comment] 2019-03-27 18:32
Ok, we really need to clarify what an issue is or isn't, otherwise it's messy for everybody. Here, we are talking about a specific feature called the contact page, we do not need two different issues.

**Comment by buckwierd** [comment] 2019-03-27 18:38
If we have a dedicated contact-us page where we can place a contact form, then this can be closed.
Here's an example of what I mean with 

> As a solution we might take in consideration creating a simple contact us page with a simple email contact form, like the book a call form.

https://enterpriseelectrical.ie/contact/

**Comment by lcoenen** [comment] 2019-03-27 18:42
@buckwierd From now on we will follow the rules described here for issues and commit.

https://medium.com/@danielfeelfine/commit-verbs-101-why-i-like-to-use-this-and-why-you-should-also-like-it-d3ed2689ef70

**Comment by buckwierd** [comment] 2019-03-27 18:45
Thanks Loic. We will. A step forward towards a better workflow :)

**Comment by lcoenen** [comment] 2019-04-01 19:04
This is a duplicate of #113

**Closed by lcoenen** 2019-04-01 19:04 UTC
Labels: UX, enhancement, question
