### ISSUE TITLE
Reminder to HR people that their employees are booking pubs

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#114] opened 2019-03-27 11:23 UTC
One of the reasons some HR people could not consider this is that they personally don't book pubs and forget to consider the fact that their employees do book pubs.

So we need to say that. We need to remind them that their employees are booking pubs to host their parties and celebrations.

This is the idea:

![refreshin party memory](https://user-images.githubusercontent.com/39112974/55072153-42e84680-5082-11e9-8200-26b67fad0a0a.jpg)

Right before the "This is how it works" title, we put the following line:

"**Your employees already book pubs to host their parties and celebrations (birthdays, promotions, graduations, farewells, etc.) so why not give them another reason to celebrate?**"

Yes, the full line in bold text.

Thanks 👍

**Comment by RohrerHope** [comment] 2019-03-27 11:32
Fixing the phrase:

"**Your employees already book pubs to host their parties and celebrations (birthdays, promotions, graduations, farewells, etc.) so why not give them another reason to celebrate.**"

I removed the "?" at the end of the sentence.

👍

**Comment by lcoenen** [comment] 2019-03-27 18:18
This have been added directly on `staging`.

**Comment by RohrerHope** [comment] 2019-03-27 18:44
> This have been added directly on `staging`.

Thanks. It's missing the bold letters. 👍 

Also please note that on Staging the Employees Benefit is not there as it is in Master.

**Comment by RohrerHope** [comment] 2019-03-29 18:19
Added it to be pushed to master this week.

Please be aware of the bold letters ;) 

Thanks 👍

**Comment by buckwierd** [comment] 2019-04-01 13:31
@RohrerHope & @lcoenen here we have a good example why I wanted to have dedicated tags with "Radu on it" etc. The issue is assigned to me and Loic works on it. It's not a big deal but I can't check every single issue that is assigned to me in detail before I start working on it, to be sure that no one took over.

What's the status with this now?

**Comment by lcoenen** [comment] 2019-04-01 14:28
@buckwierd it's done as stated in the commit above. It is true we should be careful of updating the assignees.

**Comment by RohrerHope** [comment] 2019-04-01 17:13
Approved in staging 👍🏼

**Comment by RohrerHope** [comment] 2019-04-01 18:18
Approved in staging 👍

**Closed** 2019-04-01 19:00 UTC
Labels: UX, enhancement, frontend, urgent
