### ISSUE TITLE
Fix Community Guidelines page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#166] opened 2019-04-28 11:28 UTC
**What's to be fixed**:

When you click on Community Guidelines this is where you land:

![Screen Shot 2019-04-28 at 12 26 32](https://user-images.githubusercontent.com/39112974/56863648-f78ec400-69b0-11e9-94c3-75d1aeafcc17.jpg)

When was this change reported? How was this change tested?

**What's the expected behavior:**

Community Guidelines should have a proper page and not be mixed up with the Privacy Policy page, or any other page.

**What happens in reality (screenshot):**

![Screen Shot 2019-04-28 at 12 26 32](https://user-images.githubusercontent.com/39112974/56863657-23aa4500-69b1-11e9-9132-e144e09239c9.jpg)

**Priority (tag accordingly):** `urgent` 
**Domain (tag accordingly):** `frontend` / `backend`
**Branch**: `hotfix-fix-community-guidelines` (derived from `master`)

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment] 2019-04-28 14:42
Here is the root causes: 

- This work should have been done with issue #110, but the community guidelines haven't been populated.
- When merging and closing this branch, this issue haven't been caught.
- The `staging` version haven't been correctly tested before the launch.

We will have to be more careful next time.

**Comment by lcoenen** [comment] 2019-04-28 15:26
**What have been done**: Populated the Community Guideline page
**Pushed to**: `hotfix-fix-community-guidelines`
**Tag somebody**: @buckwierd
**PR**: #171 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Closed by lcoenen** 2019-04-28 15:26 UTC
Labels: UX, bug, frontend, urgent

**Comment by buckwierd** [comment] 2019-04-28 15:53
The issue has been implemented/fixed correctly.
