### ISSUE TITLE
Change the green highlighting colour to our green

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#79] opened 2019-02-15 15:52 UTC
![green highliting colour](https://user-images.githubusercontent.com/39112974/52867776-8ec9d680-3139-11e9-9591-789fed60ec5c.jpg)

Can we change the green highlighting colour to our green? Also to the green colour in those automatic texts.

Thanks 👍

**Comment by buckwierd** [comment] 2019-02-15 17:22
Will do asap.

**Comment by RohrerHope** [comment] 2019-02-17 09:03
In the case of the green highlight at the bottom of the text fields.

This is how it looks when it's activated
![screen shot 2019-02-17 at 08 56 14](https://user-images.githubusercontent.com/39112974/52910632-4bcf4680-3292-11e9-8f9c-98d7a91eb2d1.jpg)

And it changes to the other bottom colour when I deactivate it

![screen shot 2019-02-17 at 08 56 24](https://user-images.githubusercontent.com/39112974/52910639-5be72600-3292-11e9-9993-b4147f12a06c.jpg)

So it will be a matter of deactivating the first one and changing the colour of the second one.

In the case of dropdown selectors where the bottom colour of the field is green, this is the element

![screen shot 2019-02-17 at 08 57 45](https://user-images.githubusercontent.com/39112974/52910645-7e793f00-3292-11e9-9576-4eea134d76cb.jpg)

In that case, we need to change the bottom colour of that element, because if we deactivate it, it goes to our orange, as shown below

![screen shot 2019-02-17 at 08 57 59](https://user-images.githubusercontent.com/39112974/52910656-a5d00c00-3292-11e9-8995-2ececfea30b6.jpg)

For the green text below the email of the account, that says that the email is verified, this is the element

![screen shot 2019-02-17 at 08 58 33](https://user-images.githubusercontent.com/39112974/52910661-bc766300-3292-11e9-98c4-8f8d435a3a6b.jpg)

If you deactivate it, it will not move to orange but it will go to a grey colour. So, in that case, we need to change the colour of the element.

**Comment by buckwierd** [comment] 2019-02-18 18:15
Updated the "successColor":
--successColor: #7FB800;
--successColorDark: #74A500;

successColorDark was definde by me, as a darker tone of our main green color #7FB800

@RohrerHope If this doesn't suit your desires, we'll have to define the colors from scratch again, based on the Flex definitions ColorDark, ColorLight, failColor, ColorNegative etc., which I don't recommend at this stage.

@lcoenen this was pushed on 4-adjust-the-static-centent. Fell free to close after pushing to master.

**Comment by lcoenen** [comment] 2019-02-20 13:26
@buckwierd Nothing have been pushed to branch 4. Are you sure you pushed?

**Comment by lcoenen** [comment] 2019-02-20 13:30
The change have been pushed to `staging`. Could you confirm that the issue is fixed before I push it to `master`?

**Comment by RohrerHope** [comment] 2019-02-20 13:44
I confirm that the new green is on staging.

@buckwierd 

When we talked about the buttons I understood that buttons would be our orange colour. I see the Request to Book button is the new green. Are we not having all our buttons in our orange with solid or ghost mode?

Thanks 👍

**Comment by buckwierd** [comment] 2019-02-20 14:36
Green looks ok on my end too.

@RohrerHope We need to define the colors and write them down, for the design to work properly. Last time we had to speed up the meeting because Nero was closing. Because the colors are controlled by the global color file (how I like to call it), we need to exactly define them from scratch. 

It's not as easy as you're used to "just change the color for a button" anymore. The colors are now controlled by variables like "successColorLight", "successColorDark" etc. We'll discuss this either of FR or on SA :)

**Comment by RohrerHope** [comment] 2019-02-20 14:39
@buckwierd 

Understood. Thanks.

**Closed** 2019-03-01 19:48 UTC
Labels: cosmetic, frontend
