### ISSUE TITLE
Fix styling of `copyright` section on Mobile

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#115] opened 2019-03-27 15:08 UTC
Given the fact that we are still very early stage and few people know about us, one of the concerns organisations might have about Whichost is if we are a legal company and if we are properly registered.

So the idea here is to put a note at the bottom of the page where we say we are a Limited company and we give our registration number (which is public information).

Here's the idea:

![legal information](https://user-images.githubusercontent.com/39112974/55087421-fc0a4900-50a1-11e9-8943-5574e02e46a0.jpg)

The registration number is 624254.

👍

**Comment by lcoenen** [comment] 2019-03-27 18:08
Do you need the capitalisation or is it ok like that? 
![image](https://user-images.githubusercontent.com/1237971/55101111-4b10a800-50bb-11e9-91c3-402f68f537f8.png)

**Comment by RohrerHope** [comment] 2019-03-27 18:41
> Do you need the capitalisation or is it ok like that?
> ![image](https://user-images.githubusercontent.com/1237971/55101111-4b10a800-50bb-11e9-91c3-402f68f537f8.png)

Looks great Loic. 👍 Thanks

**Comment by RohrerHope** [comment] 2019-04-01 18:13
This needs improvement in the mobile view. It's not great

**Comment by RohrerHope** [comment] 2019-04-01 18:14
![IMG_1500](https://user-images.githubusercontent.com/39112974/55349744-66f8bd00-54b2-11e9-942d-40638c7200e8.PNG)

Here you can see the view on mobile.

**Comment by lcoenen** [comment] 2019-04-01 19:29
I put it like that. It's not perfect, but better than before. 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/1237971/55354141-decbe500-54bc-11e9-9320-3185825eeb9c.png">

**Comment by lcoenen** [comment] 2019-04-01 19:33
@RohrerHope Could you check that it's ok for you on `staging` and then comment on the PR?

**Comment by RohrerHope** [comment] 2019-04-01 19:34
Not perfect but better than before, so we can move forward with this fix to master. 👍

**Comment by RohrerHope** [comment] 2019-04-01 19:41
![Screen Shot 2019-04-01 at 20 40 59](https://user-images.githubusercontent.com/39112974/55354799-81d12e80-54be-11e9-8e92-7b3da8db9d73.jpg)

@lcoenen 

Registration on master is showing on two parts now.

**Comment by RohrerHope** [comment] 2019-04-01 19:52
@buckwierd 

Please let's find a proper solution for this so it works correctly and we can remove that additional column of the registration on the footer asap.

Thanks 👍

**Comment by RohrerHope** [comment] 2019-04-01 20:37
When I tested the mobile version on Chrome using Inspect it looked fine, but when doing so on my phone, this is what happens with the registration text:

![IMG_1501](https://user-images.githubusercontent.com/39112974/55357942-2440e000-54c6-11e9-8ee8-c098576d10e5.PNG)

It overlaps the Menu right above it. It doesn't look good.

Is it easier for us to discard this for now? That way we can rework on it from scratch on staging? @lcoenen

**Comment by lcoenen** [comment] 2019-04-03 16:10
This have been hot-fixed on `master`. Here is the current behaviour: 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/1237971/55494805-6a678200-5633-11e9-8c5f-e6cf469f7642.png">

**Comment by lcoenen** [comment] 2019-04-10 16:01
@buckwierd I add the registration infos in the Field provided by sharetribe, but it's designed for one line only. Here's the behaviour on mobile: 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1237971/55894504-2126ad80-5bb2-11e9-8a8a-6bb4f1b06c8a.png">

I decreased the size of the fond, but I need it vertically centered. Could you have a look at that? 

You'll find the corresponding class in `src/components/Footer/Footer.css`, class `organisationCopyrightMobile`.

**Comment by buckwierd** [comment] 2019-04-12 08:49
@lcoenen looked into it. The information being aligned left is correct. There is nothing we need to change here. You can continue with pushing etc.

**Comment by RohrerHope** [comment] 2019-04-17 14:16
![mobile legal information footer](https://user-images.githubusercontent.com/39112974/56294591-3441fc00-6123-11e9-88a2-1eeb91c4fea0.jpg)

Still not there.

Guys, please let's ask for help in situations like this. For how long have we been struggling with this? And if we ask for help to someone with more experience in Frontend Design we most probably would get a very straightforward answer on where the issue is.

The issue is not related to the size of the screen. The issue here is that unfortunately, we don't have the knowledge to properly implement this.

@lcoenen could Sharetribe maybe give us a hint or tip on how to solve this?

**Comment by lcoenen** [comment] 2019-04-17 14:30
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment] 2019-04-17 14:57
**What have been done**: Move registration infos to the menu directly (in plain text)
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 
**PR**: NA

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by lcoenen** [comment] 2019-04-17 14:58
![image](https://user-images.githubusercontent.com/1237971/56298163-96056480-6129-11e9-8271-b7aa9e4cb8ed.png)

**Comment by RohrerHope** [comment] 2019-04-19 16:50
Good job!

**Comment by RohrerHope** [comment] 2019-04-26 14:01
> Good job!

This one is back to the bad version. I don't know what happened there but in staging is no longer looking good.

@lcoenen 

Thanks 👍

**Closed** 2019-04-27 18:01 UTC
Labels: UX, enhancement, frontend, urgent

**Comment by buckwierd** [comment] 2019-04-27 18:29
The issue has been implemented/fixed correctly.
