### ISSUE TITLE
Change Deals to Benefits

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#177] opened 2019-04-29 07:56 UTC
**What's the improvement**: 

Deals involve business and negotiation. Our benefits are not deals, they are benefits. So we are using the wrong word to express them and it has an impact on how they are perceived.

This is an example of the Deals page, in the FAQ/Contact us page:

![No menu selection highlight](https://user-images.githubusercontent.com/39112974/56882663-29109980-6a5c-11e9-8d6c-f029fadfc8d3.jpg)

**How should it look like (screenshot or sketch)**:

All expressions of Deals, **in all pages where we talk about them**, must change to Benefits.

Here's an example on the Deals page inside FAQ/Contact us page:

![benefits](https://user-images.githubusercontent.com/39112974/56882699-447ba480-6a5c-11e9-8991-ba04d50bfc35.jpg)

**How should it work (write use case)**:

N/A, this is a text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Dell, Windows 10, Chrome, the latest version
**Branch**: Staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

**Validate**

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment] 2019-04-29 08:07
Another location of the word Deals is in the footer, under Customer we have "Deals for you", so it should say "Benefits for you" or just "Benefits".

**Comment by lcoenen** [comment] 2019-05-05 14:20
@RohrerHope This is a `Trivial` issue as it doesn't involve feature development but textual change.

**Comment by lcoenen** [comment] 2019-05-05 14:39
**What have been done**: We change mentions of Deals all accross the website. We also changed the URL. Let me know if you find anything else.
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 
**Where to test**: https://whichost-frontend-staging.herokuapp.com
**PR**: (create a PR if the branch is ready to be merged)

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Closed by lcoenen** 2019-05-05 14:39 UTC
Labels: Trivial, UX, frontend

**Comment by buckwierd** [comment] 2019-05-06 06:58
The issue has been implemented/fixed correctly.
