### ISSUE TITLE
"+Add your profile picture" not centred in image circle

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#78] opened 2019-02-15 15:50 UTC
![add your picture off circle](https://user-images.githubusercontent.com/39112974/52867619-3db9e280-3139-11e9-9479-4ea081093470.jpg)

"+Add your profile picture..." is not aligned with the circle. Is not centred.

Thanks 👍

**Comment by lcoenen** [comment] 2019-02-16 20:36
@buckwierd I'll need you to have a look at the CSS on that one? Can you tell me the element and the class it's using?

**Comment by RohrerHope** [comment] 2019-02-17 08:26
I was able to find an element that makes it look better.

The element is called: **FieldBirthdayInput.css:99**

Here's how it looks now:
![screen shot 2019-02-17 at 08 22 29](https://user-images.githubusercontent.com/39112974/52910308-808ccf00-328d-11e9-8223-da57384c2644.jpg)

Here's how it looks when I remove the style "white-space: nowrap;" from it.
![screen shot 2019-02-17 at 08 22 41](https://user-images.githubusercontent.com/39112974/52910317-a4501500-328d-11e9-9c07-6ca9bb2d5102.jpg)

We could move forward with that one for now.

**Comment by buckwierd** [comment] 2019-02-18 20:01
**white-space: pre-wrap;** was added to .avatarPlaceholderText in ProfileSettingsForm file.

@lcoenen was pushed to you over 4-adjust-the-static-centent. Feel free to close the issue after pushing to master.

**Comment by lcoenen** [comment] 2019-02-20 13:30
The change have been pushed to `staging`. Could you confirm that the issue is fixed before I push it to `master`?

**Comment by RohrerHope** [comment] 2019-02-20 13:47
I confirm this is okay in Staging 👍 

Thanks.

**Comment by buckwierd** [comment] 2019-02-20 14:31
On my side it's also fine.

**Comment by lcoenen** [comment] 2019-02-22 18:46
This will be pushed to master

**Closed by lcoenen** 2019-02-22 18:46 UTC
Labels: cosmetic, frontend
