### ISSUE TITLE
Forbid the creation of a listing where the price is 0

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#94] opened 2019-02-27 11:06 UTC
I was going through the process of creating a L, to update the P guidebook and realised that we actually accept the creating of a L where the price is 0.

I know it goes to us to approve the L, but still, we must set proper expectations up front with P and limit this field to not be 0. As we had in Go, please let's have this limit to a minimum of 3 euros.

This is also a key element to reduce no-shows and improve the quality of the customers booking because there's a need to pay and provide a card in order to complete the process.

![we accept a listing of 0 when creating a listing](https://user-images.githubusercontent.com/39112974/53485992-8188e200-3a7f-11e9-9bc2-877cf8ca0cc4.png)

Thanks 👍

**Comment by RohrerHope** [comment] 2019-02-27 11:30
I've contacted Flex support to see if they can do something on their side.

**Comment by RohrerHope** [comment] 2019-02-27 12:43
Sharetribe replied. This is not a feature in Flex. However, they said we can add a validation in the front-end in that field so it only accepts values of 3 or more.

**Comment by RohrerHope** [comment] 2019-02-28 08:44
**An idea for the price section in creating a listing**

![screen shot 2019-02-28 at 08 30 45](https://user-images.githubusercontent.com/39112974/53552881-4b596a00-3b34-11e9-8478-a066823a7c74.jpg)

This idea has three parts:

1. The field title: Next to "Price per night in euros" I added "(€3.00 minimum)" to set the proper expectations upfront.
1. The placeholder: I replaced the placeholder with "Enter your price (numbers only)…" to clearly indicate that this field only accepts numbers. (Note: if you enter a value with the € symbol, it doesn't accept it).
1. The context: Below the field, I entered a text to provide context on why setting a price is important "Why? Because it’s a simple and inexpensive way to reduce no-shows and get better customers."

As indicated above, **this is an idea.**

**Comment by lcoenen** [comment] 2019-03-06 13:45
@RohrerHope just ask me before contacting sharetribe about that. I could have told you that it's something on the frontend side.

**Comment by RohrerHope** [comment] 2019-03-06 13:48
Sounds good 👍

**Comment by lcoenen** [comment] 2019-04-10 15:35
@RohrerHope try now on `staging`.

**Comment by RohrerHope** [comment] 2019-04-10 15:53
Thanks. I can only check this later at home. 👍

**Comment by RohrerHope** [comment] 2019-04-10 18:43
Thanks for this.

Reviewed:

1. This is what it says: "Price per night in euros (minimum 3€)". Since we are moving away from saying "price per night", since we are now saying "deposit" on the L view, then this should say something like "Booking deposit in euros (minimum €9.00)". Also note how I wrote the value, euro symbol first and then 2 decimals. Let's leave it at 9 euros minimum which does not hurt anyone.
1. This is what it says under the field: "Price should be at least €0.03.". I don't know where that comes from, but we can't establish that. It needs to be aligned with the title section, so it should say "Deposit should be at least €9.00.". Please double-check the text when you are entering it, and double-check the validation on the field, because the validation is now on the €0.03, so anything above that is being accepted.

![Screen Shot 2019-04-10 at 19 36 30](https://user-images.githubusercontent.com/39112974/55904890-c77dad80-5bc8-11e9-94a2-9bccbc8452bc.jpg)

Thank you 👍

**Comment by lcoenen** [comment] 2019-04-11 19:05
@RohrerHope try now.

**Comment by RohrerHope** [comment] 2019-04-11 19:21
@lcoenen 

The filter is working better now and it's validating 9 euros. Thanks for the work.

However, you missed the opportunity to also update the text message and location of the euro symbol, as mentioned in my previous comment.

This is the current title: Price per night in euros (minimum 9.00€)

![Screen Shot 2019-04-11 at 20 16 21](https://user-images.githubusercontent.com/39112974/55985109-fbbf9f80-5c96-11e9-8971-f0793236deb5.jpg)

**Please change to this one**: Price per booking in euros (minimum €9.00)

Please double check the text and the position of the euro symbol. Also, note that I changed the expression "Price per night" to "Price per booking". 

So, to double confirm, the title will be: Price per booking in euros (minimum €9.00)

Thanks 👍

**Comment by lcoenen** [comment] 2019-04-16 14:22
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment] 2019-04-16 14:32
**What have been done**: Change in translations (replaced 'night' by 'booking' and moved the euro symbol)
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1237971/56218337-b2879b00-605c-11e9-8b41-39d7257744c0.png">

**Comment by RohrerHope** [comment] 2019-04-17 14:01
![on mobile price verification](https://user-images.githubusercontent.com/39112974/56293690-7ff3a600-6121-11e9-8822-f12784488a52.jpg)

On the desktop is working fine, and the validation is also working.

On mobile, you can view what happens in the image attached to this comment.

The title of the field does not adapt properly to the size of the screen. That's the coding (or CSS) of that element because it should adapt and change to the next line, and not go over the screen.

Thanks.

**Comment by lcoenen** [comment] 2019-04-19 19:19
We talked about putting `min` instead of `minimum`.

**Comment by lcoenen** [comment] 2019-04-24 18:34
This works on Chrome 73 on Android 7.0, on Chrome 73 on Mac OS Mojave and on Safari 12.1 on Mac OS Mojave. 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1237971/56684466-b86a2580-66c7-11e9-880b-09b94cad4477.png">

I added a `wrap-text` directive in that line's CSS. It could fix the issue, but I am unable to test it.

We're going to proceed with that issue since it have been fixed. There's no reasons to delay the lunch for a fix issue, even if it introduce a minor bug.

This will be fixed ASAP. 

@RohrerHope, please test the issue again and create a proper issue if the problem is still there.

**Closed** 2019-04-24 18:36 UTC
Labels: Trivial, UX, frontend, invalid

**Comment by RohrerHope** [comment] 2019-04-26 15:28
As agreed. We will move forward with this and I will create a new issue to solve the CSS issue with the field title.
