### ISSUE TITLE
Help center additional UX update

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#73] opened 2019-02-14 13:10 UTC
When Aoife and my sister had to find the help center, they had difficulties with it. In addition to issue #71 we might take in consideration to create a dedicated Help area in the footer.

This can be done by replacing "Top cities" with "Help". 
The new help area can contain all help related information like:
- Help center
- Book a call
- Guidelines
- Fees

Looking into the future of Whichost where we'll enter new markets, the footer area "Top cities" will have to be removed anyway due to the complexity of the platform hosting L's of different categories (Pubs, restaurants, coffeeshops etc.) in many countries.

**Comment by lcoenen** [comment] 2019-03-15 13:08
#96 the pages for the help center have been created, we just need to populate them :)

**Comment by lcoenen** [comment] 2019-03-15 13:15
Duplicate of #71 .

**Closed by lcoenen** 2019-03-15 13:15 UTC
Labels: UX
