### ISSUE TITLE
Add Recommend Gift link when no pubs found

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#162] opened 2019-04-27 18:29 UTC
**What's the improvement**: 

With the launch of the "Recommend Gift" benefit to our users, we now need to regularly remind them of this, especially at moments in which the benefit properly relates to.

This is what our users see today when they search for pubs in a location with no listings:

![No results improvement to show recommend gift 001](https://user-images.githubusercontent.com/39112974/56853590-f1053b80-6921-11e9-9b76-b922c1d893cf.jpeg)

**How should it look like (screenshot or sketch)**:

With the launch of our "Recommend Gift" benefit, we now change that message and add a reminder to our users of the benefit, and a link for more information.

This is the proposal:

![No results improvement to show recommend gift 002](https://user-images.githubusercontent.com/39112974/56853603-17c37200-6922-11e9-9c10-968a4539ba6e.jpeg)

Not only the original message from the platform changes, but now we add two other lines which make reference to the "Recommend Gift" benefit, and a link for more information.

- The original message "Could not find any listings." change to "Whoops! No pubs listed here yet, but you can still celebrate."

The new orange texts in the design are a copy-paste from the "Recommend Gift" benefit page.

**How should it work (write use case)**:

When users search for pubs in a location where we have no listings, we show them this message.

When they click on "Learn more..." it will take them to the "Recommend Gift" benefit page.

**Priority (tag accordingly):** `regular`
**Domain (tag accordingly):** `frontend`
**Branch**: `add-recommend-gift-link-when-no-pub-founds`
**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

**Validate**

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment] 2019-04-27 18:46
Assigning to @lcoenen for the reason:
This is related to the translation `"SearchFilters.noResults": "Could not find any listings.",` in the translation file `en.json` and we need a fix like the one for the payment method message, where we implemented the "contact us" link.

**Comment by lcoenen** [comment] 2019-04-28 21:53
**What have been done**: Add the redirection to recommend Page
<img width="792" alt="image" src="https://user-images.githubusercontent.com/1237971/56870518-76fbb200-6a08-11e9-91a8-dfbe5c26e291.png">
 on SearchFilters
**Pushed to**: `add-recommend-gift-link-when-no-pubs-found` -> `staging`
**Tag somebody**: @RohrerHope 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by RohrerHope** [comment] 2019-04-29 07:14
@lcoenen @buckwierd 

Thanks for this. However, why so many of the details of the original designed have been changed without any discussion?

1. "Could not find any listings" remains like it when I clearly indicate in the design that that line should say "Whoops! No pubs listed here yet, but you can still celebrate." **Why?**
1. The entire message for the recommend reward is now in one line, all bold, the main text in black and only "Learn more..." in our orange. **Why?**

This is the design I provided with the issue:

![56853603-17c37200-6922-11e9-9c10-968a4539ba6e](https://user-images.githubusercontent.com/39112974/56880807-1bf0ac00-6a56-11e9-973c-e41c6c1dbbc6.jpeg)

This is what was implemented:

![no results found](https://user-images.githubusercontent.com/39112974/56880843-362a8a00-6a56-11e9-9187-af041fb9bfe3.jpg)

In between me presenting this issue and the implementation of it, nobody consulted or asked about the design, and just implemented this. **Why?**

Why do we continue to waste time like this? If someone has a different idea for a proposal or design then present it before implementing it. Ask about it. But if there are no questions or concerns raised, then it's expected that the original design presented will be the one implemented.

We need to stop doing this. Please!

Thanks.

**Comment by lcoenen** [comment] 2019-04-29 11:53
This is not wasting time. I had a look at the issue and attempted to implement it in accordance to website styling described in CSS. There is no reasons why we need to add an extra new line.  

Moreover, the whole point of having a validation system is precisely to create this discussion. If you're not satisfied with the work done, just describe your issue without making accusations. Thank you.

**Comment by RohrerHope** [comment] 2019-04-29 12:12
Loic, I don't have issues with other ideas. My issue is why is a different
design was implemented without first discussing it? And then putting the
issue to be reviewed without settings any expectations?

Before making changes, that's when we discuss to propose alternatives, not
after. And certainly, not after implementing an almost completely different
style without any discussion.

You also did not mention anything related to not changing the first line of
the message. Which is also in the design and in the description of the
issue.

All elements were identified when posting the issue and most of it was
changed, without any discussion, and then implemented. That's where the
problem is. Not on presenting other ideas or alternatives.

If you ask me to review something, and there has been no discussion on the
design or the content, then I will expect that my original idea will be
there, and not something almost completely different.

**If you think there's a better way, then propose the idea before
implementing anything. Let's discuss the options before doing any coding.
That's saving time.**

Going back to the design:

1. Please update the first line of the text where we say we didn't find
anything (info the original description of the issue).
2. Remove the bold font style from the message related to the Recommend
Reward.
3. Align the text to the left, not centre.
4. Change the colour of the text to our orange.

Tanks 👍🏼

**Comment by lcoenen** [comment] 2019-04-29 12:19
I indeed incorrectly staged the issue and didn't change the main sentence. Nevertheless, the underlying mechanisms have been implemented in both mobile and desktop and the rest are trivial matters. Please don't forget that there are a lot going on under the hood that needs to be taken care of, even though you don't see it directly.

The whole point of having a validation system being to catch those mistakes and discuss them, I don't understand the fuss. Just refuse the changes as their are incomplete without constantly re-thinking the way we work and writing a novel about it. I heard the complains about developpement speed, and tried to go faster, but you cannot expect me to be error-free after 10+ hours. Against, this is exactly the point of validation.

Moreover, before the style guidelines comes out, the CSS vars are our way to enforce a consistant styling across the website. I created the messages in accordance to the semantics tags in use in other part of the website. This is bad practice to add ad-hoc styling as this is going to complicate implementations of new features and maintenance on the long run.

**Comment by RohrerHope** [comment] 2019-04-29 13:09
Okay. I understood what you are saying.

My proposal is that in the future we don't use coding review as a review of
a proposed design. Let's keep them as two different things.

Regarding the design, what can we do then? Can my latest requests be
implemented? If not, can we remove the bold formatting and change the
colour to our orange?

This is important because we need to clearly highlight that message, and
using our orange is the best way to do it to call the eyes of the users to
that message.

Thanks.

**Comment by lcoenen** [comment] 2019-04-30 15:27
@RohrerHope Without guidelines, I need to look at the code and try before I can tell if it's possible or not. Design and coding are not different things now. If you want to separate them, don't use the github issues for this kind of discussions.

**Comment by lcoenen** [comment] 2019-04-30 15:44
**What have been done**: 

We removed the weight of the recommend gift message.
We corrected the failure message.

![image](https://user-images.githubusercontent.com/1237971/56974367-9f99be00-6b66-11e9-9729-a1830da51af2.png)

**Pushed to**: `add-recommend-gift-link-when-no-pubs-found` -> `staging`
**Tag somebody**: @RohrerHope 

As you can see, there is no distinction between _Learn more..._ and the rest of the text. This make sense given that our orange is used for links across the website and not for highlighting things. Those links are only underlined when the user point them with its mouse. 

Except if you want me to change this behavior across the website, this design is not applicable. 

![image](https://user-images.githubusercontent.com/1237971/56974686-3bc3c500-6b67-11e9-867b-0d0c12255b99.png)

**Comment by RohrerHope** [comment] 2019-04-30 16:02
Thanks @lcoenen 

Observations:

1. Euro symbol goes in front of the numbers, so 15€ is actually €15.
1. The orange colour is fine. When people's eyes are called to read the orange message, once they read "Learn more..." they will know where to click. "Learn more..." is a common used hyperlinked text.
1. Regarding the usage of the orange colour, it's not only used for links. We have other sections of the platform in which we use the orange colour to highlight texts that are not links.
1. The mobile view message for no results is different:

![mobile view no results](https://user-images.githubusercontent.com/39112974/56975725-4ed79480-6b69-11e9-991e-d7b8d8206989.jpg)

Can we also change the mobile message for no results to match the new one we created?

Thanks 👍

**Comment by lcoenen** [comment] 2019-05-01 14:54
1. That will be changed.
2. Again, I am uncomfortable with applying a random styling here. This is bad UX not to respect convention we establish all across the website. 
3. If there are some other labels (other than links) using this color on the website, this shouldn't be. I'm almost certain this wasn't the case in the Flex template and keep in mind if we ever change the styling, we will have to change it by hand if we keep applying random styling without giving it any long-term thoughts.
4. As stated above, no we cannot. There's a space contraint and I cannot add wordy sentences on a tiny mobile screen. Give me something shorter if you want me to add it.

**Comment by RohrerHope** [comment] 2019-05-03 06:12
@lcoenen 

I'll wait for your push to staging so I can test how the message looks like, the one we wrote yesterday.

Question: How many characters do we have for the mobile version of this text?

Thanks.

**Comment by lcoenen** [comment] 2019-05-04 14:57
**What have been done**: We updated the message on mobile and removed the "Learn more" link. The whole message is not a link.
![image](https://user-images.githubusercontent.com/1237971/57180607-41c8e700-6e82-11e9-85be-5b3046c9b51f.png)

**Pushed to**: `add-recommend-gift-link-when-no-pubs-found`
**Tag somebody**: @RohrerHope 
**PR**: #183

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Closed** 2019-05-04 15:09 UTC
Labels: enhancement, frontend

**Comment by lcoenen** [comment] 2019-05-05 13:48
@RohrerHope There have been an issue with the branch somehow (see PR #184). Please use the link provided (on `staging`) to test.

**Comment by buckwierd** [comment] 2019-05-06 07:05
The issue has been implemented/fixed correctly.

**Comment by RohrerHope** [comment] 2019-05-06 09:09
@lcoenen 

If possible, please update the phrase to "Click here to earn a €15 gift card to use with over 2,000 shops in Ireland & the UK, just by recommending us a pub and celebrating there."

Why? Because in our T&C we indicate that the benefit is for both countries and because One4all work also in the UK.

If not possible, then I'll create a new hot fix issue after this push to master.

Thanks.
