### ISSUE TITLE
Messages between users

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#59] opened 2019-02-13 14:51 UTC
After Aoife replied to Treasa’s message, she got a bounce back as shown in the screenshot ![Image](https://i.imgur.com/RofN95m.jpg)

**Comment by lcoenen** [comment] 2019-02-13 14:53
Emails are not front-end related. I don't have the access for the Google account.

**Comment by lcoenen** [comment] 2019-02-13 14:53
Did she answered directly to the email?

**Comment by buckwierd** [comment] 2019-02-13 15:02
She clicked on the button “Reply to Treasa” and got forwarded on a blank page. 
- I’ll look into this one

Afterwards she replied directly through her email software
- This doesn’t have to be investigated further, as it is normal behavior for our no-Reply email address

I’ll get back with news

**Comment by lcoenen** [comment] 2019-02-13 15:04
I think it's the same issue as #57, since they are redicted to the same page.

**Comment by buckwierd** [comment] 2019-02-13 15:13
I’m waiting for Aoife to forward me the emails so I can see if the link is broken.

**Comment by lcoenen** [comment] 2019-02-13 15:23
> Aoife forwarded me the email. The issue is a broken link.
> 
> We had this before:
> marketplace.url is using Whichost.com
> Our domain is still market.whichost.com
> 
> I’ll quick fix it later like the other emails yesterday

@buckwierd you commented on the wrong issue.

**Comment by buckwierd** [comment] 2019-02-13 15:25
Sorry. Please focus on the urgent issues Loïc.

**Comment by buckwierd** [comment] 2019-02-13 17:45
Update
This is how I just replicated the blank page issue:
After logging in to the account I clicked on "Inbox". Under "Hosting" I see both requests from Treasa. At this stage it doesn't matter where I click (Treasa's name, pending etc.) I land on a blank page.

We had a similar issue where clicking on edit L forwarded us on a blank page. 

I hope you can work with this, @lcoenen

**Comment by buckwierd** [comment] 2019-02-13 18:14
@lcoenen this is the different one Loic... 
Please check my last comment here...

**Comment by buckwierd** [comment] 2019-02-13 18:14
This is the one that you're asking for

**Comment by lcoenen** [comment] 2019-02-13 18:26
This is linked with the DNS and should be commented on #52 . As stated above, this issue is a duplicate of both #52 and #57. This issue will be closed.

**Closed by lcoenen** 2019-02-13 18:26 UTC
Labels: backend, duplicate, urgent
