### ISSUE TITLE
Accessing the “Profile Settings” page "from an account migrated from Go" forwards on a blank page

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#86] opened 2019-02-19 16:15 UTC
We had this issue in the past too:
After logging in and clicking on “Profile Settings” you land on a blank page. 

Can you please take a look at it @lcoenen

**Comment by lcoenen** [comment] 2019-02-19 16:49
Is there any error message?

**Comment by buckwierd** [comment] 2019-02-19 17:17
@lcoenen and @RohrerHope here's how it behaves exactly

When I access the Profile Settings page from Aoife's profile (new created after the migration was done), the page opens and everything is fine.

When I access the Profile Settings page from my radu@whichost.com profile (created before the migration), I get the blanc page.

Now I don't know if this is something that we need to investigate. If not, then we can close the issue, since new profiles work fine.

**Comment by buckwierd** [comment] 2019-02-19 17:22
<img width="1384" alt="screenshot 2019-02-19 at 17 22 13" src="https://user-images.githubusercontent.com/45966402/53034394-f7cb8a00-346a-11e9-9804-8a7c1f03d512.png">

The error in the console.

**Comment by RohrerHope** [comment] 2019-02-19 17:34
I've edited the title of the issue to clarify where it's coming from.

**The issue is real** and it happens to the accounts that were migrated from Go. The profile settings page is blank for all of them.

I tested with a couple of listing account we created and the issue is there. Blank profile settings page.

Probably because those profiles from Go did not have the information that the profile settings page is requesting to show.

**Comment by lcoenen** [comment] 2019-02-20 12:07
Ok, the issue is indeed that the accounts doesn't have the birthday information. 

This have to be fixed in `util/data.js` in function `ensureCurrentUser`.

**Comment by lcoenen** [comment] 2019-02-20 12:09
Created branch `profile-setting-empty-current-user` from `master`

**Comment by lcoenen** [comment] 2019-02-20 12:18
Erratum, the issue apparently goes deeper than that: 
![image](https://user-images.githubusercontent.com/1237971/53091297-7f67d600-3509-11e9-9d1e-2ca507b15b2c.png)
Apparently the birthday is recorded twice, both in the user and in `protectedData`. 

Which one should I use?

**Comment by lcoenen** [comment] 2019-02-20 13:25
This should be fixed. @buckwierd could you confirm?

**Comment by buckwierd** [comment] 2019-02-20 14:31
Confirming that this works fine.

**Closed** 2019-02-21 09:00 UTC
Labels: bug
