### ISSUE TITLE
Include the UK in gift card message when no pubs found

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#189] opened 2019-05-06 09:59 UTC
**What's to be corrected**: 

When no pubs are found in the search, the phrase "Click here to earn a €15 gift card to use with over 2,000 shops in Ireland just by recommending us a pub and celebrating there." needs to include the UK.

![Screen Shot 2019-05-06 at 10 53 08](https://user-images.githubusercontent.com/39112974/57218555-7c02c780-6fed-11e9-9e2f-c27f88e0142c.jpg)

**How should it look like (screenshot or sketch)**:

The phrase should say: "Click here to earn a €15 gift card to use with over 2,000 shops in Ireland & the UK, just by recommending us a pub and celebrating there."

In both desktop and mobile views.

**Please, always notice capitalisations and other grammatical elements in sentences. They are there for a reason.**

**How should it work (write use case)**:

N/A. Text improvement.

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Mac, latest Mac OS, Chrome, the latest version
**Branch**: PR to master

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment] 2019-05-06 11:26
Duplicate of #190

**Closed by lcoenen** 2019-05-06 11:26 UTC
Labels: Trivial, frontend, urgent
