### ISSUE TITLE
Change "book a call" button to "request a Callback"

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#128] opened 2019-04-05 19:03 UTC

**Comment by RohrerHope** [comment] 2019-04-06 07:57
Issue #129 is a duplicate. I created it before refreshing the issues page, so I did not see that you had already created this one.

Notes:

- There is no space between 'call' and 'back', it's a callback.
- The text in the button must be "Request a Callback" (with that formatting).
- Please observe the paragraphs that come before the buttons as they might have references to "book a call" type of message. In those cases, please replace accordingly to "request a callback".

Thanks 👍

**Comment by RohrerHope** [comment] 2019-04-06 08:14
@buckwierd @lcoenen 

The page content for the callback has been updated: https://info.whichost.com/eng/book-a-call.

I did not update the URL to not create more confusion or work.

**Comment by RohrerHope** [comment] 2019-04-06 08:19
In case we want to change the URL, even because we will eventually close Squarespace, then I would suggest we move forward with our Calendly account.

Our Calendly URL is: https://calendly.com/whichost

👍

**Comment by lcoenen** [comment] 2019-04-10 15:19
@RohrerHope Can I close this?

**Comment by RohrerHope** [comment] 2019-04-10 15:23
I have not been informed that I can test it :) 

Where do I test it?

**Comment by lcoenen** [comment] 2019-04-10 15:32
On `staging`

**Comment by RohrerHope** [comment] 2019-04-10 15:53
Thanks. I can only check this later at home. 👍

**Comment by RohrerHope** [comment] 2019-04-10 18:34
@buckwierd 

This needs your review. The 'Request a Callback' text goes all the way to the edges of the button. Doesn't look nice.

Thanks 👍

**Comment by buckwierd** [comment] 2019-04-12 08:46
Can't look into it because every time I switch the branch, I'm getting asked to commit the `.env` file. @lcoenen I need your help tonight, to fix this on my laptop.

**Comment by lcoenen** [comment] 2019-04-16 14:39
@buckwierd do you still need help on this? It's a small cosmetic issue, it shouldn't delay the next launch.

**Comment by buckwierd** [comment] 2019-04-16 19:02
@lcoenen same issue here with compiling. Here's what I see when I select the branch "set-up-deals-pages"

Error: clientId must be provided
▼ 3 stack frames were expanded.
wt
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
new t
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
h
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
▲ 3 stack frames were expanded.
./src/index.js
src/index.js:86
  83 | // eslint-disable-next-line no-underscore-dangle
  84 | const preloadedState = window.__PRELOADED_STATE__ || '{}';
  85 | const initialState = JSON.parse(preloadedState, sdkTypes.reviver);
> 86 | const sdk = createInstance({
  87 |   transitVerbose: config.sdk.transitVerbose,
  88 |   clientId: config.sdk.clientId,
  89 |   secure: config.usingSSL,
View compiled
▼ 6 stack frames were expanded.
__webpack_require__
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 6157b8c9b9a6d4ce7fe4:678
fn
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 6157b8c9b9a6d4ce7fe4:88
0
http://localhost:3000/static/js/bundle.js:224726:18
__webpack_require__
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 6157b8c9b9a6d4ce7fe4:678
(anonymous function)
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 6157b8c9b9a6d4ce7fe4:724
(anonymous function)
http://localhost:3000/static/js/bundle.js:728:10
▲ 6 stack frames were expanded.

**Comment by lcoenen** [comment] 2019-04-16 19:14
@buckwierd check that the `.env` file is there and restart the server.

**Comment by buckwierd** [comment] 2019-04-17 17:22
@lcoenen I solved like this:
1. Added `.env` to `.gitignore`committed` and pushed

**Comment by buckwierd** [comment] 2019-04-24 17:04
I am working on it.

**Comment by buckwierd** [comment] 2019-04-24 17:09
@lcoenen can you please take a look at this? I can see the button named "Request a call back" on staging but locally it's still "Book a call". Do you have a solutioon for this?

**Comment by buckwierd** [comment] 2019-04-24 17:13
I am working on it, because I can now see the correct content, after Loic merged.

**Comment by buckwierd** [comment] 2019-04-24 17:19
Done. Increased the padding and width of the get in touch buttons. pull request will follow.

**Comment by lcoenen** [comment] 2019-04-26 18:39
The request a call button will point to https://calendly.com/whichost

**Comment by buckwierd** [comment] 2019-04-27 10:45
@lcoenen please change the calendly link to [https://calendly.com/whichost/30min](url)

**REASON**
It’s more user friendly, since we only offer one option of 30 minutes and there is no need for the requester to see first the page https://calendly.com/whichost.

It’s saving one step in the “request a callback” process. Currently, there are three steps you need to do, to request a callback:
1. Click on the button “Request a callback”
2. Select the “30 minutes” on calendly
3. Select a date and confirm

We could reduce it to two steps and make it easier to get in touch with us:
1. Click on the button “Request a callback”
2. Select a date and confirm

This was already confirmed with Carlos.

**Comment by lcoenen** [comment] 2019-04-27 17:14
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment] 2019-04-27 17:33
**What have been done**: The Request a Callback button now point to Calandly, and so are the links.
**Pushed to**: `staging`
**Tag somebody**:  @RohrerHope @buckwierd

**Closed** 2019-04-27 17:46 UTC
Labels: Trivial, enhancement, frontend, invalid

**Comment by buckwierd** [comment] 2019-04-27 18:23
@lcoenen @RohrerHope This can't be tested because now with the new deals pages the "request a callback" button is gone. We can link the button on the new "Contact Us" page, above the contact form. It could look like this: 

We're here to help. **Request a callback** or us the contact form to write us a message.

If we move forward with my example, this issue can be considered as valid and done, and we open a new one for the implementation of my example. 

Please comment with your thoughts.

**Comment by RohrerHope** [comment] 2019-04-27 18:45
We can patch it like that. 

Improvement proposal to the message:

"We're here to help. **Request a callback** or use the contact form to get in touch."

Why? Because we will implement the purposes into the contact form, so not always they will use it to write us a message, but they will always use it to get in touch, with a purpose. :) 

Thanks 👍

**Comment by lcoenen** [comment] 2019-04-27 19:11
> @lcoenen @RohrerHope This can't be tested because now with the new deals pages the "request a callback" button is gone. We can link the button on the new "Contact Us" page, above the contact form. It could look like this:
> 
> We're here to help. **Request a callback** or us the contact form to write us a message.
> 
> If we move forward with my example, this issue can be considered as valid and done, and we open a new one for the implementation of my example.
> 
> Please comment with your thoughts.

The new Deals page is for the next version (`2.2`). We are about to launch version `2.1` :) The discussions about what to do with the request a Callback button belongs to respective issues (#157 and #159).

Please chat me if any questions arise.
