### ISSUE TITLE
Booking acceptance

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#57] opened 2019-02-13 14:13 UTC
According to @buckwierd, it looks like the publican cannot accept a booking. 

When going to the Inbox page, this leads to a blank page.

**Comment by lcoenen** [comment] 2019-02-13 14:37
![image](https://user-images.githubusercontent.com/1237971/52719106-dc5d0c80-2f9c-11e9-9690-b13b0c2f83b8.png)

Here is the issue. Apparently the `commission` line of the breakout isn't there.

**Comment by lcoenen** [comment] 2019-02-13 14:42
I will try with the `staging` version to avoid testing in real life.

**Comment by buckwierd** [comment] 2019-02-13 14:53
Please let me know if additional information is needed, since you’ve already found the issue 🙂

**Comment by lcoenen** [comment] 2019-02-13 15:10
The issue is also there on `staging`.

**Comment by lcoenen** [comment] 2019-02-13 15:21
![image](https://user-images.githubusercontent.com/1237971/52722165-ff8aba80-2fa2-11e9-9e2d-b801a98792e6.png)

**Comment by buckwierd** [comment] 2019-02-13 15:21
Aoife forwarded me the email. The issue is a broken link. 

We had this before:
marketplace.url is using Whichost.com 
Our domain is still market.whichost.com

I’ll quick fix it later like the other emails yesterday

**Comment by RohrerHope** [comment] 2019-02-13 15:46
If it's of any value, I remember when testing in the test environment, I was able to accept or reject a booking request.

**Comment by lcoenen** [comment] 2019-02-13 16:29
So after I fixed the commission according to those instruction, the `LineItemProviderComissionMaybe` isn't giving anything (and for cause, there is no provider commission at all, so why is it triggered?>

**Comment by lcoenen** [comment] 2019-02-13 18:00
@buckwierd @RohrerHope It is working on `staging` and I just pushed it to `master`. Could you check that the issue is fixed?

**Comment by buckwierd** [comment] 2019-02-13 18:00
I'll quick fix it over the transaction emails. One moment.

**Comment by buckwierd** [comment] 2019-02-13 18:06
@lcoenen I've quick fixed it by replacing {{marketplace.url}} with https://market.whichost.com
It's pushed to you. Please send it to master so we can test it.

**Comment by lcoenen** [comment] 2019-02-13 18:07
Dude, wrong issue again.

**Comment by buckwierd** [comment] 2019-02-13 18:09
This is the correct issue:
The P can't accept the booking out of the email due to the fucking wrong DNS settings! This was fixed now with the quick fix. 

Please let me now when it was pushed to master.

**Comment by RohrerHope** [comment] 2019-02-13 18:10
Aoife has the listings with the booking requests. In 

I can't test that now.

**Comment by RohrerHope** [comment] 2019-02-13 18:10
Sorry

**Comment by lcoenen** [comment] 2019-02-13 18:10
@buckwierd on which branch did you pushed it?

**Comment by buckwierd** [comment] 2019-02-13 18:12
As we agreed for small changes:
4-adjust-the-static-centent

**Comment by lcoenen** [comment] 2019-02-13 18:12
There is two different issue: the one with the blank page when going to Inbox and the one with the email. Please create a different one.

**Comment by lcoenen** [comment] 2019-02-13 18:32
This have been fixed the branch `booking-acceptance-issue`. It is fixed

**Closed** 2019-02-13 18:32 UTC
Labels: bug, frontend, urgent
