### ISSUE TITLE
Improve contact us in Payment Information

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#132] opened 2019-04-11 07:45 UTC
When did we test this in staging? It's live on master and has a clear design issue.

![Screen Shot 2019-04-11 at 08 40 59](https://user-images.githubusercontent.com/39112974/55939432-a010fa00-5c35-11e9-8b9a-4d2a395b6140.jpg)

This is clearly not properly implemented. There's a dot before "contact us" which should be a space.

Good job on the "contact us" hyperlink to the mailto:. 

Please, let's fix this quickly.

Thanks 👍

**Comment by lcoenen** [comment] 2019-04-11 17:30
Duplicate of #88

**Closed** 2019-04-11 17:30 UTC
Labels: UX, frontend, urgent
