### ISSUE TITLE
Improve the Employee Benefits page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#159] opened 2019-04-27 09:02 UTC
**What's the improvement**: 

1. Improve the Corporate benefit page design to simplify it and make it cleaner.
1. Change "Employees Benefit" to "Corporate Benefit" all around the page and menu.
1. Change all references to "Deals" to "Benefits"

**How should it look like (screenshot or sketch)**:

![Birthday Gift Proposal Page 003](https://user-images.githubusercontent.com/39112974/56847496-71e91680-68d3-11e9-8107-421cfc2e4bab.jpeg)

**How should it work (write use case)**:

- When users click on the contact us button it will take them to the contact form. We will create a new purpose for this case if one has not been already created.

**Priority (tag accordingly):** `urgent` / `regular` (`next` column) or `non-urgent` / `wontfix` (`backlog` column)
**Domain (tag accordingly):** `frontend` / `backend`
**Tested on:** (platform, OS, browser, version)
**Branch**: (name of the branch derived from `staging` or another development another branch)

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment] 2019-04-27 18:10
Works ongoing. Here's how the coded page looks now. Waiting for #161 and #158 to be finalized, before I can finish this page.
<img width="909" alt="Screenshot 2019-04-27 at 19 09 12" src="https://user-images.githubusercontent.com/45966402/56853454-23ae3480-6920-11e9-8447-98515c8f5b31.png">

**Comment by RohrerHope** [comment] 2019-04-27 18:34
> Works ongoing. Here's how the coded page looks now. Waiting for #161 and #158 to be finalized, before I can finish this page.
> <img alt="Screenshot 2019-04-27 at 19 09 12" width="909" src="https://user-images.githubusercontent.com/45966402/56853454-23ae3480-6920-11e9-8447-98515c8f5b31.png">

Looking good @buckwierd 

The text for the terms and conditions, can we change it to normal text in a normal colour with normal sizing?

Airbnb on their side they don't highlight them. I believe this is healthier.

![Airbnb referral programme page](https://user-images.githubusercontent.com/39112974/56853716-6f161200-6923-11e9-9dd1-d0d199f622af.png)

**Comment by lcoenen** [comment] 2019-04-28 16:57
This issue is a duplicate of #157.

@buckwierd let's try to keep thing organised: one issue per feature, one branch per issue, one Pull request per branch. 

Here, you work on both page on the same branch, inside the same commit.

**Closed by lcoenen** 2019-04-28 16:57 UTC
Labels: UX, enhancement, frontend
