### ISSUE TITLE
Improve fee message in booking page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#221] opened 2019-06-01 18:27 UTC
**What's to be corrected**: 

We now donate 100% of the 10% fee that we charge users, and we need to start talking about it. One spot where we need to talk about it is exactly where the user makes the booking.

This is how we address the user fee today:

![Screen Shot 2019-06-01 at 19 12 02](https://user-images.githubusercontent.com/39112974/58752158-32998100-84a2-11e9-9a08-88e02cc611f5.jpg)

Let's change that phrase to this one:

"100% of the user fees are donated! They are consolidated every three months and donated to a local non-profit organisation."

**How should it look like (screenshot or sketch)**:

![Screen Shot 2019-06-01 at 19 23 00](https://user-images.githubusercontent.com/39112974/58752188-c5d2b680-84a2-11e9-9dc3-a88aafbc488c.jpg)

**Notice here important new elements**

- The colour of the text is not that light grey, but our blue #0D2C54. This is a proposal since we can't use our orange and we can't use our green as they are already been used in the platform for other purposes. But we need to not put that message in light grey because it's very important.
- I added a line jump between "Total price" and the donation message. That line jump is not there in the original version. In that version, the asterisk message comes right after "Total price", no line jump. Please add the line jump.

**How should it work (write use case)**:

![Screen Shot 2019-06-01 at 19 23 00](https://user-images.githubusercontent.com/39112974/58752216-2a8e1100-84a3-11e9-9bf4-a8613e04c349.jpg)

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: Staging

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment] 2019-06-05 15:43
@lcoenen @Shane-Walsh 

We need this implemented quick. I just made modifications to the listings descriptions in which I make a reference to our donation of the 10% fee, so the message in this section needs to be aligned with it.

Thanks.

**Comment by lcoenen** [comment] 2019-06-05 16:33
@RohrerHope Thanks for letting us know. This will be done as soon as possible.

**Comment by TommyJackson85** [comment] 2019-06-06 17:28
**What has been done**: Booking note text changed to: "100% of the user fees are donated! They are consolidated every three months and donated to a local non-profit organisation." Changed css of feeInfo class, with the font colour changed to dark blue, and the top margin changed to 1.25em. Now there is a line break between Total Cost and the Booking note,  and the booking note is changed to dark blue. 
**Pushed to**: improve-fee-message-in-booking-page
**Tag somebody**: @lcoenen @RohrerHope 
**PR**: (create a PR if the branch is ready to be merged)

**Asking for validation**: 

- Check on mobile and on a desktop if the issue has been correctly fixed.
- If everything is correct, move the card to the accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Closed by TommyJackson85** 2019-06-06 17:28 UTC
Labels: Trivial, UX, frontend
